### ISSUE TITLE
Exception when reading large data sets.

### ISSUE THREAD

**Issue by twhnat** [MD2Korg/DataExporter#3]
Tested on an 8GB SQLite database file

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.String.substring(String.java:1957)
	at java.lang.String.split(String.java:2341)
	at java.lang.String.split(String.java:2410)
	at org.md2k.cerebralcortex.TSV.<init>(TSV.java:39)
	at org.md2k.dataexporter.DataExport.generateJSON(DataExport.java:97)
	at org.md2k.dataexporter.DataExport.generateGzipJSON(DataExport.java:158)
	at org.md2k.dataexporter.DataExport.generateGzipJSON(DataExport.java:147)
	at org.md2k.dataexporter.DataExport.publishGzipJSONData(DataExport.java:466)
	at Main.main(Main.java:86)

**Comment by twhnat** [comment]
Fixed, #4
